server:
  port: 9000

spring:
  # json提交时 [Date Calendar] 的全局序列化和反序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: ${project.artifactId}
  profiles:
    active: ${profiles.active}
  config:
    import:
      - classpath:config/${spring.profiles.active}/captcha.yml
      - classpath:config/${spring.profiles.active}/doc.yml
      - classpath:config/${spring.profiles.active}/log.yml
      - classpath:config/${spring.profiles.active}/mail.yml
      - classpath:config/${spring.profiles.active}/minio.yml
      - classpath:config/${spring.profiles.active}/oauth2.yml
      - classpath:config/${spring.profiles.active}/sap.yml
      - classpath:config/${spring.profiles.active}/tenant.yml
      - classpath:config/${spring.profiles.active}/wx.yml
      - classpath:config/${spring.profiles.active}/xss.yml
      - classpath:config/${spring.profiles.active}/mybatis-plus.yml
  #thymeleaf模板配置
  thymeleaf:
    cache: false                   # 这个开发配置为false，避免改了模板还要重启服务器
    prefix: classpath:/templates/  #模板文件视图前缀，默认是classpath:/templates/，可不用配置
    suffix: .html                  #模板文件视图后缀，默认是.html，可不用配置
    check-template-location: true  #检查模板位置，可不用配置
    encoding: utf-8                #编码字符集，默认为utf-8，可不用配置
    mode: HTML                     #模板的模式，默认为HTML，可不用配置
    servlet:
      content-type: text/html       #模板的内容类型，默认为text/html，可不用配置
  servlet:
    multipart:
      # 单文件大小限制
      max-file-size: 10MB
      # 总上传大小限制
      max-request-size: 10MB

# 开放端点
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: true

flowable:
  async-executor-activate: false # 关闭定时任务JOB
  database-schema-update: true   # 将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
