spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks

breeze:
  aesSecret: 1234567890123456
  security:
    ignore-urls:
      # Monitor
      - "/actuator/**"
      # Local file storage
      - "/img/**"
      # Data sources & Report generation
      - "/druid/**"
      - "/ureport/**"