spring:
  redis:
    host: breeze-redis
    port: 6379
    password: breeze
  datasource:
    url: jdbc:mysql://breeze-mysql:3306/breeze_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 启用内置过滤器（第一个 stat必须，否则监控不到SQL）
      filters: stat,wall
      # 配置WebStatFilter，用于采集web关联监控的数据
      web-stat-filter:
        # 开启监控
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      filter:
        stat:
          db-type: mysql
          # 开启慢sql监控，超过()s 就认为是慢sql，记录到日志中
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10
        wall:
          db-type: mysql
          config:
            multi-statement-allow: true
      stat-view-servlet:
        # 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        enabled: true
        reset-enable: false
        allow: "127.0.0.1"
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        deny:

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
  configuration:
    jdbc-type-for-null: null
    # 逻辑删除
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 搜索指定包别名
  typeAliasesPackage: com.breeze.**.entity
