spring:
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: 123@qq.com
    password: 123
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
    from-address: 123@qq.com
