breeze:
  # 本地硬盘存储配置
  storage:
    local:
      path: /usr/local/breeze/
      nginx-host: http://localhost:9000/img/
  # oss s3 配置
  oss:
    s3:
      endpoint: http://10.100.201.35:9092
      accessKey: BS2F32UehPanopBG
      secretKey: 4i0hyIfnxlZA6EbojRqKFFgbZ0nb6amK
