server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: ${project.artifactId}
  main:
    allow-circular-references: true
  profiles:
    active: ${profiles.active}
    group:
      "dev": "dev-db,dev-capture,dev-doc,dev-mail,dev-storage,dev-wx,dev-flowable"
      "pro": "pro-db,pro-capture,pro-doc,pro-mail,pro-storage,pro-wx,pro-flowable"

  servlet:
    multipart:
      # 单文件大小限制
      max-file-size: 10MB
      # 总上传大小限制
      max-request-size: 10MB
  boot:
    admin:
      client:
        # Admin 服务端地址
        url: http://127.0.0.1:8000
        instance:
          prefer-ip: true
        # server 用户名
        username: admin
        # server 密码
        password: admin

# 开放端点
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: true

breeze: # 权限过滤路径
  security:
    ignore-urls:
      - "/ws/**"
      - "/img/**"
      - "/actuator/**"
      - "/captcha/**"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/*.html"
      - "/**/*.html"
      - "/**/*.ico"
      - "/druid/**"
      - "/swagger-ui/**"
      - "/swagger-resources/**"
      - "/v3/api-docs/**"
      - "/webjars/**"
      - "/doc.html"
  tenant: # 多租户过滤路径
    ignore-urls:
      - "/captcha/**"
      - "/sys/common/selectTenant"
      - "/breeze/**"
      - "/process/**"
  xss: # xss过滤路径
    ignore-urls:
      - "/process/definition/**"
  jwt:
    rsa-private-key: classpath:app.key
    rsa-public-key: classpath:app.pub
  log:
    enable: true

logging:
  file:
    name: ./logs/${spring.application.name}/${spring.application.name}.log
  config: classpath:logback-spring.xml

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
  configuration:
    jdbc-type-for-null: null
    # 逻辑删除
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # mybatis-plus配置控制台打印完整带参数SQL语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 搜索指定包别名
  typeAliasesPackage: com.breeze.**.entity
