breeze:
  # 本地硬盘存储配置
  storage:
    local:
      path: /usr/local/breeze/
      nginx-host: http://localhost:9000/img/
  # oss s3 配置
  oss:
    s3:
      endpoint: http://localhost:9092
      minio-root-user: admin
      minio-root-password: 12345678
