server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: ${project.artifactId}
  main:
    allow-circular-references: true
  profiles:
    active: ${profiles.active}
    group:
      "dev": "dev-db,dev-capture,dev-doc,dev-mail,dev-storage"
      "pro": "pro-db,pro-capture,pro-doc,pro-mail,pro-storage"

  servlet:
    multipart:
      # 单文件大小限制
      max-file-size: 10MB
      # 总上传大小限制
      max-request-size: 10MB
  boot:
    admin:
      client:
        # Admin 服务端地址
        url: http://127.0.0.1:8000
        instance:
          prefer-ip: true
        # server 用户名
        username: admin
        # server 密码
        password: admin

# 开放端点
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: true

breeze:
  security:
    ignore-urls:
      - "/ws/**"
      - "/img/**"
      - "/actuator/**"
      - "/captcha/**"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/*.html"
      - "/**/*.html"
      - "/**/*.ico"
      - "/druid/**"
      - "/swagger-ui/**"
      - "/swagger-resources/**"
      - "/v3/api-docs/**"
      - "/webjars/**"
      - "/doc.html"
  jwt:
    rsa-private-key: classpath:app.key
    rsa-public-key: classpath:app.pub
  log:
    enable: true

logging:
  file:
    name: ./logs/${spring.application.name}/${spring.application.name}.log
  config: classpath:logback-spring.xml
